SELECT SNAME 年,YEAR(GETDATE())-BIRTHYEAR AS 年龄 FROM S
ORDER BY BIRTHYEAR

SELECT DISTINCT SDEPT from S

SELECT SNAME FROM S
WHERE SDEPT ='软件'

SELECT SNAME,SDEPT,BIRTHYEAR FROM S
WHERE BIRTHYEAR >=1998 AND BIRTHYEAR <2000

SELECT COUNT(*) 数1,
		COUNT(GRADE) 数2,
		COUNT(DISTINCT GRADE) 数3
FROM SC

SELECT SNO,SNAME,YEAR(GETDATE())-BIRTHYEAR AS 年龄 FROM S
WHERE SDEPT ='软件' AND SEX='男'

SELECT SNO,SNAME,BIRTHYEAR FROM S
WHERE SDEPT ='软件' AND SNAME LIKE '王%'
ORDER BY SNO

SELECT CDEPT,SUM(CREDIT) AS 总学分,COUNT(CNAME)AS 课程数 FROM C
WHERE CNATURE='必修'
GROUP BY CDEPT

SELECT SNO,SNAME,SDEPT
INTO S_FEMALE
FROM S
WHERE SEX='女'

Select CNo,AVG(grade) as 'Average'
From   S inner join SC
    On S.SNo=SC.SNo 
Where Sdept='软件'
Group by CNo

SELECT a.SNO
FROM SC a JOIN SC b 
ON a.SNO=b.SNO
AND a.CNO='0121'
AND b.CNO='0125'

SELECT S.*, SC.*
FROM S RIGHT OUTER JOIN SC 
ON S.SNO=SC.SNO

SELECT S.*, SC.*
FROM S JOIN SC 
ON S.SNO=SC.SNO


